language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
notifications:
  email: false
before_install:
  - pip install cython numpy pandas scipy
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=~/ -DINSTALL_PYTHON_MODULE=ON ..
  - make
install:
  - make install
script:
  - ctest -j2
before_deploy:
  - git config --local user.name "bcoconni"
  - git config --local user.email "bcoconni@users.sourceforge.net"
  - git tag -f JSBSim-trusty-v2018a
deploy:
  provider: releases
  api_key:
    secure: QVCyxQGW/LNMxzHGekuDuEKLi9T/o8JLIX+bedty2P/xcn+3dhzEI6XTZRyO3dZgOOMJuwlrKpVqSaJl44z5wC4DyMrd/euyULgtWzWH4ffpPYabixZ2O4WCooz3ab5U/1+hYC5vLviQywvNc2YIrbPb/ugH3Xh455JrDp3xs1ZycOIHIybI2jGuWsji4FLPQTnmAmUDuNchyPrr0XwGvSEu4liEAwRdYtxqXlVdySvUp+0NJY4xuU792cWX4QSs7teK27P/EsHwggh6aK3QkEPq229PyIsukFn+yjhOi6MMr+THC1NQTWjrmXKtYuiGii5xEkuxpSHzgtjd14UTooLRV3nLjr/sDIrwUprkWQiCnauW3e3cf4cJpYw0e9+7Yq3T42jBW5uodCwTzxjdr7IUoTLBq/hMtxQ6I+pR2UPTgS72ggPHud2h+EAVoimvgxGdk0juJqThIp4bgd83I5QwFnpQlXtHdnC+SvwG4eiL/u3JAQ/0o2uUgP7de8/3XjGGNqTGWchfzvYAblwnJSP6uyULyzTKmV90eeJeXOrspVFjk9HWfCNT8vBmVN6siH2mlPxkdaWsWXEOXEADHK8fdj89Oao/A6m+A4SifVQnhZSnv6MUCBoDNnenLrZLw6GpEP52ejM4LV9VADgGb32doxbY4awsVlzjpON9blw=
  file: src/JSBSim
  skip_cleanup: true
  on:
    python: 3.6
