language: python
python:
  - "2.7"
  - "3.4"
env:
  - USE_SYSTEM_EXPAT=OFF
  - USE_SYSTEM_EXPAT=ON
notifications:
  email: false
# Skip the build of tagged branches (otherwise the same commit is built multiple times)
branches:
  except:
    - /^JSBSim-.*-v2018a.*$/
    - /^untagged-.*$/
# command to install dependencies
before_install:
  - pip install cython numpy pandas scipy
  - gem install gist
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=~/ -DINSTALL_PYTHON_MODULE=ON -DCPACK_GENERATOR=DEB -DBUILD_SHARED_LIBS=$USE_SYSTEM_EXPAT -DSYSTEM_EXPAT=$USE_SYSTEM_EXPAT ..
  - make -j2
install:
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/lib
  - make install
script:
  - ctest
after_success:
  - cpack
# If the build fails, the tests log will be uploaded to a gist under my account
# (bcoconni) so that they can be deleted when irrelevant. The output of the
# command line `gist` is the web address to the gist.
after_failure:
  - echo $GIST_TOKEN > ~/.gist
  - gist -d "JSBSim build $TRAVIS_JOB_NUMBER failed" Testing/Temporary/*.log | envsubst
before_deploy:
  - git config --local user.name "bcoconni"
  - git config --local user.email "bcoconni@users.sourceforge.net"
  - git tag "JSBSim-trusty-v2018a-$TRAVIS_BUILD_NUMBER" -m "Ubuntu Trusty 14.04 - Release - x64"
deploy:
  provider: releases
  api_key:
    secure: FHMLgbuRTSznrfMSpb3/nJIECKS0v8VFHUfC99ZpMBjZR4kxptDSPchpHzLFlrytzl1+H62w1iWChx5RYaH1MW8a/ejCUWYO0IjO6hLtG72nMJeDIBC2JzLnKN7cLqMrgEHKW7XmK3CtXGa/tXxu+KEvmbwskv3TOWGUokdUB3EI0vTLjjCQBW05VK7oSBq+7Jl4zGJumWwALP5EK7DC7McPXpLlkw5zdga+LQVcg8aDPrNwgF5kaH03b7TagYgiG2OFb4FAPvfz70RWeCRB7QQn1jOGULZ3PHz8EnNOfyBqGJ0flDyAfZcwJNY1OONW9ELnOctvzdmmU2P+KGuK4cJuzI59aRVQrwcSnnl26DU/95Hev4mdCIlPz798C3TfZu+U36uzGMurQJjE7Fg59N4WnqubhWKWu/7qRhn1uttdPm5sIcVAPpshKm8uzlsTLLMTNUMj5ZIimVbFV2lz0PbDWPnbHxHeDKgaVkIjTQy4e1XZH7IhjIVODG2PK1TnWS/6RRTBUVXxwup7Tj8HhVbLjrfPs2qLDJv70sRyKUgAqqKdGkr/7Es52y1i/io3BJqiIOpJBM5Wyzk37NCAlX4WCoqJZQbKKRQ9hH5baZaxlpz28Hc0tbAqfwFOwAOonf1+s7MBM896EoAtdKpr0Z0F/ra9ePQezTbtQhvws3g=
  file_glob: true
  file:
    - "JSBSim-devel*.deb"
    - "JSBSim_*[0-9].deb"
    - "python[2-3]-JSBSim*.deb"
  skip_cleanup: true
  on:
    python: 3.4
    condition: $USE_SYSTEM_EXPAT = ON
