language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
notifications:
  email: false
before_install:
  - pip install cython numpy pandas scipy
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=~/ -DINSTALL_PYTHON_MODULE=ON ..
  - make
install:
  - make install
script:
  - ctest -j2
before_deploy:
  - git config --local user.name "bcoconni"
  - git config --local user.email "bcoconni@users.sourceforge.net"
  - git tag -f JSBSim-trusty-v2018a
deploy:
  provider: releases
  api_key:
    secure: OP13vUIRBY6F7r+6pU8EX34O0p8OfJBoW+jwVqbQbfaTzOEBzNM06YcFAYHDcgP2D7ye8wVNPJ2H814B5BAyoV+AMY8UWlAXx2g982Q8zxAHBDW18lCMMk6fqKv09DY8h8ZXV7XX56DU2LQ6BC2V7ppQdWrUGXBwVD/bhHQ9To5TBqkPiqYIy646MECje+skeC5fS1yAT3MPu6189bQREn20icIzYKPJcWm2nbO7XWOj4pEefXaQUmEotOLRh6d822510ib+gtd06yhVTFKdMwM7fSyi/aSAKzspQN7J49/XFR6oyDFrjad38gKLbbSrsgXJbLvCC/xJ0q7Yvg5Sc812pTGQ6IvwtdmqqW1SEH8QCj6338a0CPiopKiHKZ4ihr7Ju2B69+fNTYTCc8LoPT6FOny1G9uJrKIud7zD68jH2rRQDy3ph9V57caX1Ximy55Fe8bfDHhsN71LnwEUhDHx3EVaCC0kfrdrfRG4bTbUiSWjlhUHB3wqqPcRsdsf87JXUZ+8pzQEHowwaD9gvDMjh7DQAFxkhrlQY0HXdUsIxngP9W0W8Qq913jswz3VhQds88KZwaOnTUm/4LRm/66NknPzz9lQPHZygN5ONd6TCgAdf641D3dp/cihSpIII5LcKTNZzm5qmOxE+OBZEfJesKEuoCdxtiCQlZPFoQM=
  file: src/JSBSim
  skip_cleanup: true
  on:
    python: 3.6
