language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
notifications:
  email: false
before_install:
  - pip install cython numpy pandas scipy
  - mkdir build
  - cd build
  - cmake -DCMAKE_INSTALL_PREFIX=~/ -DINSTALL_PYTHON_MODULE=ON ..
  - make
install:
  - make install
script:
  - ctest -j2
before_deploy:
  - git config --local user.name "bcoconni"
  - git config --local user.email "bcoconni@users.sourceforge.net"
  - git tag -f JSBSim-trusty-v2018a
deploy:
  provider: releases
  api_key:
    secure: sjlUYQtjKwI1cBWuUVZzPS4wrqG/MuMA6tlKkx9I4a2AwoXoiPMeH1Xp/L6uGIe17L8knuF3CZ/kojIt7qm5VQ5+Zc8Nh097SnkEfdEqZpm4k27jN+bZ6ma1kPRwcXESOuDY6nhs1wgADvU5f2yp50ZkSx8WbR8TTyM49kcmMJD1hPrgJbN8tp1As5cK8ZwZNIi9MBxOBL2nqp1B9hdxs95mzdpksJm0XDuTERZfo1HMqF9HtMbGvwioNB+LDAh5q9aV3iIoxfgPDKzNtHaopoEPRqWnTg+hfjSBqBFyZip+lmLpNV2NqDbPvhY0UmG6bfho7oVgqOvhFp5gIEIX5dist5EVMY6gj1DnPVjwlRA33tdnX2C981WpGvFJNRBV8LBHA4OMh0Hl6zHIUhSwdm0IKg+wnW10XF9NdDCSnWoa8hkzH25IB87hX5ilOggrI9k3qO6Oy2T1CIGvFxHqV1Rf+2hp9hdq47HSbqsxiVjh8DYWL23atFOEj/hKeVycC0qCvu1UT5nqTqKn+BpLPDd0WabdKSYDAZqFD9puDrRPKURKo0QbsNScHf7m4tcdoQKBXBoTHtze1zgTX3Lc6GiPIF43Z3Byd9PLuvQanj9grevX6/EPsjoLLKegTP4R/4oekdzIRKMK09XPT/PRMuczuLsLrD5D4AuNpSbr3Ug=
  file: src/JSBSim
  skip_cleanup: true
  on:
    python: 3.6
