# see: https://www.appveyor.com/docs/appveyor-yml/

image: Visual Studio 2017

version: 1.0.{build}

build_script:
- cmd: msbuild JSBSim.vcxproj /p:Configuration=Release /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: Release\JSBSim.exe
  name: JSBSim_Release_x64_v2018a

# Do not build on tags (GitHub and BitBucket)
# to avoid infinite build loops
skip_tags: true

deploy:
- provider: GitHub
  tag: JSBSim-win64-v$(appveyor_build_version)
  description: VS 2015 - Release - x64
  auth_token:
    secure: YWG8FRFWv/ylTuA1DIFNcN01uFGz7xKit8CayOMTE0orPKXhztwLmwm8MZ4IzFbr
  artifact: Release\JSBSim.exe
  prerelease: true
  on:
    branch: master
