# see: https://www.appveyor.com/docs/appveyor-yml/

version: 1.0.{build}

build_script:
- cmd: msbuild JSBSim.vcxproj /p:Configuration=Release /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: Release\JSBSim.exe
  name: JSBSim_Release_x64_v2018a

deploy:
- provider: GitHub
  tag: JSBSim-win64-v1.0.$(appveyor_build_version)
  auth_token:
    secure: YWG8FRFWv/ylTuA1DIFNcN01uFGz7xKit8CayOMTE0orPKXhztwLmwm8MZ4IzFbr
  artifact: Release\JSBSim.exe
  prerelease: true
  on:
    branch: master
